### PR TITLE
s/OpenSSL::Digest::Digest.new/OpenSSL::Digest.new/

### PR DESCRIPTION
**Pull request by JustinAiken**
> OpenSSL::Digest::Digest has been discouraged to use from very ancient era such as Ruby 1.8 and finally was deprecated recently.

This makes the gem usable on 2.1+

### CODE REVIEW

**Comment by aforward** [comment]
Thanks Justin.

**Comment by JustinAiken** [comment]
Thanks for the quick merge :)

Bonus points if you want to bump the version and push a gem ;)

**Comment by aforward** [comment]
http://rubygems.org/gems/geokit-premier

v0.1.0

**Comment by JustinAiken** [comment]
:beers:

**Pull request merged**
